name = "homelab_system"
version = "1.1.0"
description = "Distributed homelab management system using Gleam and OTP"
licences = ["MIT"]
repository = { type = "github", user = "yourusername", repo = "homelab_system" }
links = [{ title = "GitHub", href = "https://github.com/yourusername/homelab_system" }]

[dependencies]
gleam_stdlib = ">= 0.62.1 and < 1.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

# Distributed clustering
glyn = ">= 2.0.3 and < 3.0.0"
lifeguard = ">= 4.0.0 and < 5.0.0"

# Messaging & Communication
glubsub = ">= 1.2.0 and < 2.0.0"
# chip = ">= 0.9.0 and < 1.0.0"  # Temporarily disabled due to compatibility issues

# Configuration & Environment
glenvy = ">= 2.0.1 and < 3.0.0"
gleam_json = "~> 3.0.0"     # JSON configuration
yodel = "~> 1.0.1"          # Advanced config loading (Phase 2+)

# CLI & Web Interface
glint = "~> 1.2.1"          # Command-line parsing
wisp = "~> 2.0.0-rc1"       # Web framework
lustre = "~> 5.3.4"         # Frontend framework

# Utilities
youid = "~> 1.5.0"          # UUID generation

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
